### ISSUE TITLE
Library is possibly broken on recent go version

### ISSUE THREAD

**Issue by monokrome** [bjeanes/go-lifx#1]
Running `go version` says `go version go1.3 darwin/amd64` which I believe to be recent. The result from `go get github.com/bjeanes/go-lifx/client` or `go get github.com/bjeanes/go-lifx` is as follows:

``` sh
# github.com/bjeanes/go-lifx/protocol
.config/go/src/github.com/bjeanes/go-lifx/protocol/message.go:12: non-declaration statement outside function body
.config/go/src/github.com/bjeanes/go-lifx/protocol/message.go:12: syntax error: unexpected struct, expecting semicolon or newline
.config/go/src/github.com/bjeanes/go-lifx/protocol/message.go:14: non-declaration statement outside function body
.config/go/src/github.com/bjeanes/go-lifx/protocol/message.go:15: non-declaration statement outside function body
.config/go/src/github.com/bjeanes/go-lifx/protocol/message.go:16: non-declaration statement outside function body
.config/go/src/github.com/bjeanes/go-lifx/protocol/message.go:17: non-declaration statement outside function body
.config/go/src/github.com/bjeanes/go-lifx/protocol/message.go:17: syntax error: unexpected name, expecting semicolon or newline
.config/go/src/github.com/bjeanes/go-lifx/protocol/message.go:18: non-declaration statement outside function body
.config/go/src/github.com/bjeanes/go-lifx/protocol/message.go:18: syntax error: unexpected name, expecting semicolon or newline
.config/go/src/github.com/bjeanes/go-lifx/protocol/message.go:19: non-declaration statement outside function body
.config/go/src/github.com/bjeanes/go-lifx/protocol/message.go:19: too many errors
```

**Comment by bjeanes** [comment]
@monokrome sorry about that. What I have so far is pretty incomplete and experimental anyway. I had a working build locally for a few weeks but hadn't committed it because I didn't realize master was broken.

**Comment by monokrome** [comment]
:( !

**Comment by bjeanes** [comment]
The current status is that `go run lifx-snoop.go` will monitor network, decoding LIFX messages into various structs, then pretty print them on stdout.

**Comment by radar** [comment]
An update for the people at home: @bjeanes and I are working on this currently and we're getting it to a working state. Given that I'll be working for LIFX shortly, this should speed things along.

**Comment by wolfeidau** [comment]
Great work so far, we are testing it out at the moment. On and off seem to work fine however we are seeing duplicate lights being discovered.

We were planning on hacking on a fork of this over the next couple of days to get the core functions sorted for one of our beta drivers.

Will keep you posted on what we run into!

**Comment by bjeanes** [comment]
> On and off seem to work fine however we are seeing duplicate lights being discovered.

Yup that was discussed in #8. It's still early days... :)

**Comment by bjeanes** [comment]
Er that is, in [this comment](https://github.com/bjeanes/go-lifx/pull/8#issuecomment-50297978) @radar pointed out that the bulb distinction was still a TODO but I missed that and prematurely merged, I guess.

**Comment by radar** [comment]
Definitely still a TODO. I don't have two bulbs at home (I will by Friday) and so I had no chance to be able to target specific lights.

**Comment by bjeanes** [comment]
I have an idea of how to represent a "target" (device id, tag, label) which I'll hopefully prototype tonight.

**Comment by radar** [comment]
Do it!
