### ISSUE TITLE
Light discovery listening for wrong payload

### ISSUE THREAD

**Issue by bjeanes** [bjeanes/go-lifx#11]
The payload that represents a light on the network [is `LightState`](https://github.com/LIFX/lifx-gem/blob/edaf4613c1dd3458b493024282719d48685ef775/lib/lifx/network_context.rb#L165-L167), but we are listening for `DeviceStatePanGateway`, which represents a gateway (also important but for different reasons)

**Comment by bjeanes** [comment]
I addressed listening to LightState in b2d4d335bb05f6d9c32c460613e48e24e3066da6, but looking at [this lifx-gem code](https://github.com/LIFX/lifx-gem/blob/86c7082d62bac0a7aa2ed5d94da05b45c2d241b5/lib/lifx/gateway_connection.rb#L24-L31), I'm wondering if `LightGet` calls have to be sent directly to a gateway (which means opening a UDP connection _to_ the gateway) instead of just on the broadcast connection.

@chendo can you confirm/deny?

**Comment by bjeanes** [comment]
If so, it may be that what @radar had was correct but incomplete (i.e. listen for `DeviceStatePanGateway` but instead of adding a bulb, we create a connection and ask it for bulbs).

**Comment by chendo** [comment]
Nope, LightGet doesn’t have to be sent directly to a gateway

**Comment by bjeanes** [comment]
Hmm... then I need to figure out what is different between our client and the iPad client. In #13 I implemented basic `lifx-snoop` filtering so that I could find just `LightGet` messages:

``` sh-session
$ go run cli/lifx-snoop/lifx-snoop.go lightget
FROM: 192.168.11.52:56750
SIZE: 36
DATA: 000  24 00 00 34 00 00 00 00  00 00 00 00 00 00 00 00  |$..4............|
      010  4c 49 46 58 56 32 00 00  00 00 00 00 00 00 00 00  |LIFXV2..........|
      020  65 00 00 00                                       |e...|
MSG:  &{Version:1024 Target:[0 0 0 0 0 0 0 0] Site:[76 73 70 88 86 50] AtTime:0 Addressable:true Tagged:true Acknowledge:false}
      *payloads.LightGet &{}

...
```

`192.168.11.52` is my iPad and the messages are triggered after hitting the refresh button. One thing that sticks out to me is that the payloads seem to be originating from the peer port only. Not yet sure if significant.

**Comment by bjeanes** [comment]
Hah... so for comparison, our client is outputting:

``` sh-session
$ go run cli/lifx-snoop/lifx-snoop.go lightget
FROM: 192.168.11.63:53490
SIZE: 36
DATA: 000  24 00 00 34 00 00 00 00  00 00 00 00 00 00 00 00  |$..4............|
      010  4c 49 46 58 56 32 00 00  00 00 00 00 00 00 00 00  |LIFXV2..........|
      020  65 00 00 00                                       |e...|
MSG:  &{Version:1024 Target:[0 0 0 0 0 0 0 0] Site:[76 73 70 88 86 50] AtTime:0 Addressable:true Tagged:true Acknowledge:false}
      *payloads.LightGet &{}
```

I.e.: identical except for the source port. **HOWEVER**: I guess my bulbs or wifi were in a weird state last night, because running discovery now _does_ get responses returned, even when it is the only client requesting it (confirmed via `lifx-snoop`):

``` sh-session
$ go run cli/lifx/lifx.go list
Discovered bulbs:
  👧
  👦
  📈
  🔭
  📚
  👧
  👦
  📈
  🔭
  📚
  👧
  👦
  📈
  🔭
  📚
  👧
  👦
  📈
  🔭
  📚
  👧
  👦
  📈
  🔭
  📚
```

Now, to de-dupe those bulbs (#14).
